"""area pessoal: perfil mestre, vagas, candidatura emails

Revision ID: 8e0abc9aabf2
Revises: 45c020e04f4f
Create Date: 2026-06-05 02:38:52.136895+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e0abc9aabf2'
down_revision: Union[str, None] = '45c020e04f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoal_perfil_mestre',
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('tom_escrita', sa.Text(), nullable=True),
    sa.Column('habilidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projetos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experiencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('o_que_procuro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocos_curriculo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contato', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pessoal_perfil_ativo', 'pessoal_perfil_mestre', ['ativo'], unique=False)
    op.create_table('pessoal_vagas',
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('empresa', sa.String(length=300), nullable=True),
    sa.Column('link', sa.String(length=800), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('contato_nome', sa.String(length=200), nullable=True),
    sa.Column('contato_email', sa.String(length=300), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('modelo', sa.String(length=30), nullable=True),
    sa.Column('senioridade', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='quero_candidatar', nullable=False),
    sa.Column('analise_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pessoal_vagas_match_score', 'pessoal_vagas', ['match_score'], unique=False)
    op.create_index('ix_pessoal_vagas_status', 'pessoal_vagas', ['status'], unique=False)
    op.create_table('pessoal_candidatura_emails',
    sa.Column('vaga_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='email', nullable=False),
    sa.Column('destinatario', sa.String(length=300), nullable=True),
    sa.Column('assunto', sa.String(length=500), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('tom', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='rascunho', nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('variantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vaga_id'], ['pessoal_vagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pessoal_cand_emails_status', 'pessoal_candidatura_emails', ['status'], unique=False)
    op.create_index('ix_pessoal_cand_emails_vaga_id', 'pessoal_candidatura_emails', ['vaga_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pessoal_cand_emails_vaga_id', table_name='pessoal_candidatura_emails')
    op.drop_index('ix_pessoal_cand_emails_status', table_name='pessoal_candidatura_emails')
    op.drop_table('pessoal_candidatura_emails')
    op.drop_index('ix_pessoal_vagas_status', table_name='pessoal_vagas')
    op.drop_index('ix_pessoal_vagas_match_score', table_name='pessoal_vagas')
    op.drop_table('pessoal_vagas')
    op.drop_index('ix_pessoal_perfil_ativo', table_name='pessoal_perfil_mestre')
    op.drop_table('pessoal_perfil_mestre')
    # ### end Alembic commands ###
