"""auth 2fa

Revision ID: f504abb8fb1f
Revises: f79aa7549280
Create Date: 2026-06-10 01:05:50.273466+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f504abb8fb1f'
down_revision: Union[str, None] = 'f79aa7549280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_2fa',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('totp_secret_cifrado', sa.String(length=255), nullable=False),
    sa.Column('backup_codes_hash', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['auth.usuarios.id'], name='fk_auth_2fa_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_2fa', schema='auth')
    # ### end Alembic commands ###
