"""cria tabela email_outreach

Revision ID: cefb0554bd85
Revises: 2a75e04537b8
Create Date: 2026-05-29 19:51:53.531214+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cefb0554bd85'
down_revision: Union[str, None] = '2a75e04537b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outreach',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('contato_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('destinatario', sa.String(length=300), nullable=False),
    sa.Column('assunto', sa.String(length=500), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('tom', sa.String(length=100), nullable=True),
    sa.Column('canal', sa.String(length=20), server_default='email', nullable=False),
    sa.Column('follow_up_num', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='rascunho', nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('sent_message_id', sa.String(length=500), nullable=True),
    sa.Column('draft_criado_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('primeira_resposta_em', sa.DateTime(), nullable=True),
    sa.Column('resposta_trecho', sa.Text(), nullable=True),
    sa.Column('contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['email_outreach.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_outreach_contato_id', 'email_outreach', ['contato_id'], unique=False)
    op.create_index('ix_email_outreach_destinatario', 'email_outreach', ['destinatario'], unique=False)
    op.create_index('ix_email_outreach_empresa_id', 'email_outreach', ['empresa_id'], unique=False)
    op.create_index('ix_email_outreach_message_id', 'email_outreach', ['message_id'], unique=False)
    op.create_index('ix_email_outreach_status', 'email_outreach', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_outreach_status', table_name='email_outreach')
    op.drop_index('ix_email_outreach_message_id', table_name='email_outreach')
    op.drop_index('ix_email_outreach_empresa_id', table_name='email_outreach')
    op.drop_index('ix_email_outreach_destinatario', table_name='email_outreach')
    op.drop_index('ix_email_outreach_contato_id', table_name='email_outreach')
    op.drop_table('email_outreach')
    # ### end Alembic commands ###
