"""financas recorrencias + transacao vencimento e fk

Revision ID: 0b28134c9a67
Revises: 7b978dc5bf1a
Create Date: 2026-06-07 22:14:17.340631+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b28134c9a67'
down_revision: Union[str, None] = '7b978dc5bf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recorrencias',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='despesa', nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.String(length=20), server_default='mensal', nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['financas.categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conta_id'], ['financas.contas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_recorrencias_usuario_id', 'recorrencias', ['usuario_id'], unique=False, schema='financas')
    op.add_column('transacoes', sa.Column('data_vencimento', sa.Date(), nullable=True), schema='financas')
    op.create_foreign_key('fk_fin_transacoes_recorrencia', 'transacoes', 'recorrencias', ['recorrencia_id'], ['id'], source_schema='financas', referent_schema='financas', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_fin_transacoes_recorrencia', 'transacoes', schema='financas', type_='foreignkey')
    op.drop_column('transacoes', 'data_vencimento', schema='financas')
    op.drop_index('ix_fin_recorrencias_usuario_id', table_name='recorrencias', schema='financas')
    op.drop_table('recorrencias', schema='financas')
    # ### end Alembic commands ###
