"""adiciona resposta_corpo em email_outreach

Revision ID: 81e24bf42d3d
Revises: 233e64b3c333
Create Date: 2026-05-31 21:00:57.625327+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e24bf42d3d'
down_revision: Union[str, None] = '233e64b3c333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_outreach', sa.Column('resposta_corpo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_outreach', 'resposta_corpo')
    # ### end Alembic commands ###
