"""financas comprovantes

Revision ID: 94d9c1819033
Revises: e61f3a69b687
Create Date: 2026-06-07 22:29:51.628412+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94d9c1819033'
down_revision: Union[str, None] = 'e61f3a69b687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprovantes',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('transacao_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('bucket', sa.String(length=63), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('nome_original', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('extraido_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['financas.transacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_comprovantes_hash', 'comprovantes', ['hash'], unique=False, schema='financas')
    op.create_index('ix_fin_comprovantes_transacao_id', 'comprovantes', ['transacao_id'], unique=False, schema='financas')
    op.create_index('ix_fin_comprovantes_usuario_id', 'comprovantes', ['usuario_id'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_comprovantes_usuario_id', table_name='comprovantes', schema='financas')
    op.drop_index('ix_fin_comprovantes_transacao_id', table_name='comprovantes', schema='financas')
    op.drop_index('ix_fin_comprovantes_hash', table_name='comprovantes', schema='financas')
    op.drop_table('comprovantes', schema='financas')
    # ### end Alembic commands ###
