"""auth rbac papeis permissoes

Revision ID: 807b832cd51c
Revises: a1f0c0de0001
Create Date: 2026-06-09 00:16:59.053239+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807b832cd51c'
down_revision: Union[str, None] = 'a1f0c0de0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papeis',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='auth'
    )
    op.create_table('permissoes',
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='auth'
    )
    op.create_table('papel_permissoes',
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('permissao_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['auth.papeis.id'], name='fk_auth_papel_permissoes_papel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permissao_id'], ['auth.permissoes.id'], name='fk_auth_papel_permissoes_permissao', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('papel_id', 'permissao_id'),
    schema='auth'
    )
    op.create_table('usuario_papeis',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['auth.papeis.id'], name='fk_auth_usuario_papeis_papel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['auth.usuarios.id'], name='fk_auth_usuario_papeis_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'papel_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_papeis', schema='auth')
    op.drop_table('papel_permissoes', schema='auth')
    op.drop_table('permissoes', schema='auth')
    op.drop_table('papeis', schema='auth')
    # ### end Alembic commands ###
