"""financas transacoes itens pagamentos

Revision ID: cd4ee4a577be
Revises: 3fe4d1c4a738
Create Date: 2026-06-07 19:19:14.608371+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4ee4a577be'
down_revision: Union[str, None] = '3fe4d1c4a738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_competencia', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='prevista', nullable=False),
    sa.Column('origem', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('recorrencia_id', sa.UUID(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['financas.categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_transacoes_categoria_id', 'transacoes', ['categoria_id'], unique=False, schema='financas')
    op.create_index('ix_fin_transacoes_competencia', 'transacoes', ['usuario_id', 'data_competencia'], unique=False, schema='financas')
    op.create_index('ix_fin_transacoes_status', 'transacoes', ['status'], unique=False, schema='financas')
    op.create_index('ix_fin_transacoes_usuario_id', 'transacoes', ['usuario_id'], unique=False, schema='financas')
    op.create_table('transacao_itens',
    sa.Column('transacao_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['financas.categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transacao_id'], ['financas.transacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_transacao_itens_categoria_id', 'transacao_itens', ['categoria_id'], unique=False, schema='financas')
    op.create_index('ix_fin_transacao_itens_transacao_id', 'transacao_itens', ['transacao_id'], unique=False, schema='financas')
    op.create_table('transacao_pagamentos',
    sa.Column('transacao_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['financas.contas.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['financas.transacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_transacao_pagamentos_conta_id', 'transacao_pagamentos', ['conta_id'], unique=False, schema='financas')
    op.create_index('ix_fin_transacao_pagamentos_transacao_id', 'transacao_pagamentos', ['transacao_id'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_transacao_pagamentos_transacao_id', table_name='transacao_pagamentos', schema='financas')
    op.drop_index('ix_fin_transacao_pagamentos_conta_id', table_name='transacao_pagamentos', schema='financas')
    op.drop_table('transacao_pagamentos', schema='financas')
    op.drop_index('ix_fin_transacao_itens_transacao_id', table_name='transacao_itens', schema='financas')
    op.drop_index('ix_fin_transacao_itens_categoria_id', table_name='transacao_itens', schema='financas')
    op.drop_table('transacao_itens', schema='financas')
    op.drop_index('ix_fin_transacoes_usuario_id', table_name='transacoes', schema='financas')
    op.drop_index('ix_fin_transacoes_status', table_name='transacoes', schema='financas')
    op.drop_index('ix_fin_transacoes_competencia', table_name='transacoes', schema='financas')
    op.drop_index('ix_fin_transacoes_categoria_id', table_name='transacoes', schema='financas')
    op.drop_table('transacoes', schema='financas')
    # ### end Alembic commands ###
