"""financas cartoes faturas compras parcelas

Revision ID: 7b978dc5bf1a
Revises: cd4ee4a577be
Create Date: 2026-06-07 22:03:14.345846+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b978dc5bf1a'
down_revision: Union[str, None] = 'cd4ee4a577be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('bandeira', sa.String(length=50), nullable=True),
    sa.Column('dia_fechamento', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('limite', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_cartoes_usuario_id', 'cartoes', ['usuario_id'], unique=False, schema='financas')
    op.create_table('compras',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=20), server_default='cartao', nullable=False),
    sa.Column('cartao_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cartao_id'], ['financas.cartoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['categoria_id'], ['financas.categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_compras_cartao_id', 'compras', ['cartao_id'], unique=False, schema='financas')
    op.create_index('ix_fin_compras_usuario_id', 'compras', ['usuario_id'], unique=False, schema='financas')
    op.create_table('faturas',
    sa.Column('cartao_id', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='aberta', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cartao_id'], ['financas.cartoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cartao_id', 'mes_referencia', name='uq_fin_faturas_cartao_mes'),
    schema='financas'
    )
    op.create_index('ix_fin_faturas_cartao_id', 'faturas', ['cartao_id'], unique=False, schema='financas')
    op.create_table('parcelas',
    sa.Column('compra_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tem_juros', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valor_juros', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('fatura_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['financas.compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fatura_id'], ['financas.faturas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_parcelas_compra_id', 'parcelas', ['compra_id'], unique=False, schema='financas')
    op.create_index('ix_fin_parcelas_fatura_id', 'parcelas', ['fatura_id'], unique=False, schema='financas')
    op.create_index('ix_fin_parcelas_vencimento', 'parcelas', ['vencimento'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_parcelas_vencimento', table_name='parcelas', schema='financas')
    op.drop_index('ix_fin_parcelas_fatura_id', table_name='parcelas', schema='financas')
    op.drop_index('ix_fin_parcelas_compra_id', table_name='parcelas', schema='financas')
    op.drop_table('parcelas', schema='financas')
    op.drop_index('ix_fin_faturas_cartao_id', table_name='faturas', schema='financas')
    op.drop_table('faturas', schema='financas')
    op.drop_index('ix_fin_compras_usuario_id', table_name='compras', schema='financas')
    op.drop_index('ix_fin_compras_cartao_id', table_name='compras', schema='financas')
    op.drop_table('compras', schema='financas')
    op.drop_index('ix_fin_cartoes_usuario_id', table_name='cartoes', schema='financas')
    op.drop_table('cartoes', schema='financas')
    # ### end Alembic commands ###
