"""observabilidade: ai_calls + pipeline_events

Revision ID: 80161977071a
Revises: 0001_initial
Create Date: 2026-05-29 00:27:55.645337+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80161977071a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('agente', sa.String(length=50), server_default='desconecido', nullable=False),
    sa.Column('operacao', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('prompt_chars', sa.Integer(), nullable=True),
    sa.Column('resposta_chars', sa.Integer(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('custo_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('empresa_cnpj', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_calls_agente', 'ai_calls', ['agente'], unique=False)
    op.create_index('ix_ai_calls_created_at', 'ai_calls', ['created_at'], unique=False)
    op.create_index('ix_ai_calls_empresa_cnpj', 'ai_calls', ['empresa_cnpj'], unique=False)
    op.create_index('ix_ai_calls_sucesso', 'ai_calls', ['sucesso'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ok', nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('empresa_cnpj', sa.String(length=20), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_events_created_at', 'pipeline_events', ['created_at'], unique=False)
    op.create_index('ix_pipeline_events_empresa_cnpj', 'pipeline_events', ['empresa_cnpj'], unique=False)
    op.create_index('ix_pipeline_events_evento', 'pipeline_events', ['evento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_events_evento', table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_empresa_cnpj', table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_created_at', table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index('ix_ai_calls_sucesso', table_name='ai_calls')
    op.drop_index('ix_ai_calls_empresa_cnpj', table_name='ai_calls')
    op.drop_index('ix_ai_calls_created_at', table_name='ai_calls')
    op.drop_index('ix_ai_calls_agente', table_name='ai_calls')
    op.drop_table('ai_calls')
    # ### end Alembic commands ###
