"""auth tentativas_login

Revision ID: 390ea0e0f51d
Revises: 807b832cd51c
Create Date: 2026-06-09 00:47:33.678708+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390ea0e0f51d'
down_revision: Union[str, None] = '807b832cd51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_login',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('ix_auth_tentativas_email_created', 'tentativas_login', ['email', 'created_at'], unique=False, schema='auth')
    op.create_index('ix_auth_tentativas_ip_created', 'tentativas_login', ['ip', 'created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tentativas_ip_created', table_name='tentativas_login', schema='auth')
    op.drop_index('ix_auth_tentativas_email_created', table_name='tentativas_login', schema='auth')
    op.drop_table('tentativas_login', schema='auth')
    # ### end Alembic commands ###
