"""auth auditoria

Revision ID: f79aa7549280
Revises: 390ea0e0f51d
Create Date: 2026-06-09 00:57:54.457336+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79aa7549280'
down_revision: Union[str, None] = '390ea0e0f51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('ix_auth_auditoria_evento_created', 'auditoria', ['evento', 'created_at'], unique=False, schema='auth')
    op.create_index('ix_auth_auditoria_usuario_created', 'auditoria', ['usuario_id', 'created_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_auditoria_usuario_created', table_name='auditoria', schema='auth')
    op.drop_index('ix_auth_auditoria_evento_created', table_name='auditoria', schema='auth')
    op.drop_table('auditoria', schema='auth')
    # ### end Alembic commands ###
