"""score first-class em empresas

Revision ID: 233e64b3c333
Revises: cefb0554bd85
Create Date: 2026-05-31 20:23:26.368363+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233e64b3c333'
down_revision: Union[str, None] = 'cefb0554bd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('score', sa.Integer(), nullable=True))
    op.create_index('ix_empresas_score', 'empresas', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_empresas_score', table_name='empresas')
    op.drop_column('empresas', 'score')
    # ### end Alembic commands ###
