"""financas contas e categorias

Revision ID: f1d8647d25f4
Revises: a5d6d0ad5b73
Create Date: 2026-06-07 19:04:13.806266+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d8647d25f4'
down_revision: Union[str, None] = 'a5d6d0ad5b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria_pai_id', sa.UUID(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_pai_id'], ['financas.categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_categorias_pai_id', 'categorias', ['categoria_pai_id'], unique=False, schema='financas')
    op.create_table('contas',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_contas_usuario_id', 'contas', ['usuario_id'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_contas_usuario_id', table_name='contas', schema='financas')
    op.drop_table('contas', schema='financas')
    op.drop_index('ix_fin_categorias_pai_id', table_name='categorias', schema='financas')
    op.drop_table('categorias', schema='financas')
    # ### end Alembic commands ###
