"""freela_agente_pessoal

Revision ID: a09c2bcb4148
Revises: a7c3e1f9d2b8
Create Date: 2026-06-14 18:19:05.018832+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a09c2bcb4148'
down_revision: Union[str, None] = 'a7c3e1f9d2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoal_freela_plataforma',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('url_base', sa.String(length=300), nullable=True),
    sa.Column('config_comissao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lance_minimo_padrao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoal_freela_cliente',
    sa.Column('plataforma_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('projetos_publicados', sa.Integer(), nullable=True),
    sa.Column('projetos_pagos', sa.Integer(), nullable=True),
    sa.Column('pagamento_verificado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('membro_desde', sa.String(length=50), nullable=True),
    sa.Column('ja_me_pagou_usd', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plataforma_id'], ['pessoal_freela_plataforma.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoal_freela_projeto',
    sa.Column('plataforma_id', sa.UUID(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('faixa_orcamento_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('faixa_orcamento_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('habilidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prazo_estimado', sa.String(length=100), nullable=True),
    sa.Column('status_no_site', sa.String(length=50), nullable=True),
    sa.Column('n_propostas_concorrentes', sa.Integer(), nullable=True),
    sa.Column('n_interessados', sa.Integer(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analise_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['pessoal_freela_cliente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['pessoal_freela_plataforma.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoal_freela_proposta',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('valor_cotado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('horas_estimadas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_liquido_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('texto_enviado', sa.Text(), nullable=True),
    sa.Column('projetos_destacados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('habilidades_destacadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prazo_proposto', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='rascunho', nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_resposta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_perda', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['pessoal_freela_projeto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pessoal_freela_projeto_cliente', 'pessoal_freela_projeto', ['cliente_id'])
    op.create_index('ix_pessoal_freela_proposta_projeto', 'pessoal_freela_proposta', ['projeto_id'])
    op.create_index('ix_pessoal_freela_proposta_status', 'pessoal_freela_proposta', ['status'])
    # NOTA: o autogenerate detectou drift pré-existente (orcamentos TIMESTAMP→
    # DateTime e índice ix_fin_transacoes_linha_digitavel). Removido daqui de
    # propósito — esta migration é só do agente freela.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pessoal_freela_proposta_status', table_name='pessoal_freela_proposta')
    op.drop_index('ix_pessoal_freela_proposta_projeto', table_name='pessoal_freela_proposta')
    op.drop_index('ix_pessoal_freela_projeto_cliente', table_name='pessoal_freela_projeto')
    op.drop_table('pessoal_freela_proposta')
    op.drop_table('pessoal_freela_projeto')
    op.drop_table('pessoal_freela_cliente')
    op.drop_table('pessoal_freela_plataforma')
    # ### end Alembic commands ###
