"""financas bot_rascunhos

Revision ID: 233a2397398b
Revises: 94d9c1819033
Create Date: 2026-06-07 22:57:17.728543+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '233a2397398b'
down_revision: Union[str, None] = '94d9c1819033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_rascunhos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_bot_rascunhos_usuario_id', 'bot_rascunhos', ['usuario_id'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_bot_rascunhos_usuario_id', table_name='bot_rascunhos', schema='financas')
    op.drop_table('bot_rascunhos', schema='financas')
    # ### end Alembic commands ###
