"""observabilidade: ai_calls + pipeline_events refatorado

Revision ID: 2a75e04537b8
Revises: 80161977071a
Create Date: 2026-05-29 00:40:30.813302+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a75e04537b8'
down_revision: Union[str, None] = '80161977071a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_calls', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('ai_calls', sa.Column('tokens_output', sa.Integer(), nullable=True))
    op.drop_column('ai_calls', 'token_input')
    op.drop_column('ai_calls', 'token_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_calls', sa.Column('token_output', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_calls', sa.Column('token_input', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ai_calls', 'tokens_output')
    op.drop_column('ai_calls', 'tokens_input')
    # ### end Alembic commands ###
