"""financas leituras_consumo

Revision ID: e61f3a69b687
Revises: 0b28134c9a67
Create Date: 2026-06-07 22:21:20.748494+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61f3a69b687'
down_revision: Union[str, None] = '0b28134c9a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leituras_consumo',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('leitura_atual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('leitura_anterior', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('consumo', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transacao_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['financas.transacoes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='financas'
    )
    op.create_index('ix_fin_leituras_mes', 'leituras_consumo', ['mes_referencia'], unique=False, schema='financas')
    op.create_index('ix_fin_leituras_usuario_tipo', 'leituras_consumo', ['usuario_id', 'tipo'], unique=False, schema='financas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_leituras_usuario_tipo', table_name='leituras_consumo', schema='financas')
    op.drop_index('ix_fin_leituras_mes', table_name='leituras_consumo', schema='financas')
    op.drop_table('leituras_consumo', schema='financas')
    # ### end Alembic commands ###
